package DataDictionary.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.SModifiersImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class DataDictionary__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xb7df9610c91c472eL, 0xb4856407763b5456L, 0x6d04cb7a96e885ffL, "DataDictionary.structure.DataDictionary");

  public static final SMethod<Integer> getNumberOfStructure_id6O4MREmX0Ep = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getNumberOfStructure").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("6O4MREmX0Ep").build();
  public static final SMethod<Integer> getNumberOfSet_id6O4MREmXJSU = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getNumberOfSet").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("6O4MREmXJSU").build();
  public static final SMethod<Integer> getNumberOfAggregation_id6ttyxz4_zbK = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getNumberOfAggregation").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("6ttyxz4_zbK").build();
  public static final SMethod<Boolean> structureNameAlreadyExist_id6ttyxz4_N83 = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.class)).name("structureNameAlreadyExist").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("6ttyxz4_N83").build(SMethodBuilder.createJavaParameter(String.class, ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getNumberOfStructure_id6O4MREmX0Ep, getNumberOfSet_id6O4MREmXJSU, getNumberOfAggregation_id6ttyxz4_zbK, structureNameAlreadyExist_id6ttyxz4_N83);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static int getNumberOfStructure_id6O4MREmX0Ep(@NotNull SNode __thisNode__) {
    return ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.structures$76Gs)).count();
  }
  /*package*/ static int getNumberOfSet_id6O4MREmXJSU(@NotNull SNode __thisNode__) {
    int number = 0;
    for (SNode set : SLinkOperations.getChildren(__thisNode__, LINKS.structures$76Gs)) {
      if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(set, LINKS.structure$4tLW), CONCEPTS.Set$5_)) {
        number++;
      }
    }
    return number;
  }
  /*package*/ static int getNumberOfAggregation_id6ttyxz4_zbK(@NotNull SNode __thisNode__) {
    int number = 0;
    for (SNode agg : SLinkOperations.getChildren(__thisNode__, LINKS.structures$76Gs)) {
      if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(agg, LINKS.structure$4tLW), CONCEPTS.Aggregation$GW)) {
        number++;
      }
    }
    return number;
  }
  /*package*/ static Boolean structureNameAlreadyExist_id6ttyxz4_N83(@NotNull SNode __thisNode__, String name) {
    for (SNode structureDefinition : SLinkOperations.getChildren(__thisNode__, LINKS.structures$76Gs)) {
      if (SPropertyOperations.getString(structureDefinition, PROPS.name$MnvL).equals(name)) {
        return true;
      }
    }
    return false;
  }

  /*package*/ DataDictionary__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Integer) getNumberOfStructure_id6O4MREmX0Ep(node));
      case 1:
        return (T) ((Integer) getNumberOfSet_id6O4MREmXJSU(node));
      case 2:
        return (T) ((Integer) getNumberOfAggregation_id6ttyxz4_zbK(node));
      case 3:
        return (T) ((Boolean) structureNameAlreadyExist_id6ttyxz4_N83(node, (String) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink structures$76Gs = MetaAdapterFactory.getContainmentLink(0xb7df9610c91c472eL, 0xb4856407763b5456L, 0x6d04cb7a96e885ffL, 0x6d04cb7a96eae25dL, "structures");
    /*package*/ static final SContainmentLink structure$4tLW = MetaAdapterFactory.getContainmentLink(0xb7df9610c91c472eL, 0xb4856407763b5456L, 0x13db5904c2c0bff9L, 0x13db5904c2c0bffcL, "structure");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Set$5_ = MetaAdapterFactory.getConcept(0xb7df9610c91c472eL, 0xb4856407763b5456L, 0x13db5904c2c0c001L, "DataDictionary.structure.Set");
    /*package*/ static final SConcept Aggregation$GW = MetaAdapterFactory.getConcept(0xb7df9610c91c472eL, 0xb4856407763b5456L, 0x13db5904c2c0bfc8L, "DataDictionary.structure.Aggregation");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
