package DataDictionary.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import DataDictionary.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Aggregation:
        return new Aggregation_TextGen();
      case LanguageConceptSwitch.DataDictionary:
        return new DataDictionary_TextGen();
      case LanguageConceptSwitch.ExclusiveSpecialization:
        return new ExclusiveSpecialization_TextGen();
      case LanguageConceptSwitch.Field:
        return new Field_TextGen();
      case LanguageConceptSwitch.IElement:
        return new IElement_TextGen();
      case LanguageConceptSwitch.NonExclusiveSpecialization:
        return new NonExclusiveSpecialization_TextGen();
      case LanguageConceptSwitch.Set:
        return new Set_TextGen();
      case LanguageConceptSwitch.StructureDefinition:
        return new StructureDefinition_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.DataDictionary$r5)) {
        String fname = getFileName_DataDictionary(root);
        String ext = getFileExtension_DataDictionary(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_DataDictionary(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_DataDictionary(SNode node) {
    return ".dd";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DataDictionary$r5 = MetaAdapterFactory.getConcept(0xb7df9610c91c472eL, 0xb4856407763b5456L, 0x6d04cb7a96e885ffL, "DataDictionary.structure.DataDictionary");
  }
}
