package DataDictionary.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Field_Constraints extends BaseConstraintsDescriptor {
  public Field_Constraints() {
    super(CONCEPTS.Field$o3);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Field$o3 = MetaAdapterFactory.getConcept(0xb7df9610c91c472eL, 0xb4856407763b5456L, 0x13db5904c2c0bfe2L, "DataDictionary.structure.Field");
  }
}
