package DataDictionary.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import DataDictionary.behavior.DataDictionary__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class quick_fix_structure_def_unique_name_QuickFix extends QuickFix_Runtime {
  public quick_fix_structure_def_unique_name_QuickFix() {
    super(new SNodePointer("r:220831a1-1acb-4fbb-ba0f-68c947a9bb41(DataDictionary.typesystem)", "7855627377421187180"));
  }
  public String getDescription(SNode node) {
    return "Quick fix unique structure name!";
  }
  public void execute(SNode node) {
    Integer num = ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(((SNode) quick_fix_structure_def_unique_name_QuickFix.this.getField("structDef")[0]), CONCEPTS.DataDictionary$r5, false, false), LINKS.structures$76Gs)).count();
    while (DataDictionary__BehaviorDescriptor.structureNameAlreadyExist_id6ttyxz4_N83.invoke(SNodeOperations.getNodeAncestor(((SNode) quick_fix_structure_def_unique_name_QuickFix.this.getField("structDef")[0]), CONCEPTS.DataDictionary$r5, false, false), "Structure " + num)) {
      num++;
    }
    SPropertyOperations.assign(((SNode) quick_fix_structure_def_unique_name_QuickFix.this.getField("structDef")[0]), PROPS.name$MnvL, "Structure" + num);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DataDictionary$r5 = MetaAdapterFactory.getConcept(0xb7df9610c91c472eL, 0xb4856407763b5456L, 0x6d04cb7a96e885ffL, "DataDictionary.structure.DataDictionary");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink structures$76Gs = MetaAdapterFactory.getContainmentLink(0xb7df9610c91c472eL, 0xb4856407763b5456L, 0x6d04cb7a96e885ffL, 0x6d04cb7a96eae25dL, "structures");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
